/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-06-30 06:10:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class line_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1561823191150L));
    _jspx_dependants.put("/WEB-INF/pages/common/define.jsp", Long.valueOf(1561823191419L));
    _jspx_dependants.put("jar:file:/C:/magic/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/magic-frontend/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098685890000L));
    _jspx_dependants.put("jar:file:/C:/magic/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/magic-frontend/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098685890000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/common/header1.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title_for_header_jsp", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Màn hình đăng ký hoi vien", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".modal-window.large {\r\n");
      out.write("    width: 72%;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    box-shadow: 10px 10px 60px #555;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    padding: 15px 5%;\r\n");
      out.write("}\r\n");
      out.write(".abc{\r\n");
      out.write("height: 500px;\r\n");
      out.write("}\r\n");
      out.write("#lineTable th{\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write("#lineTable td{\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write(".h1TimKiem{\r\n");
      out.write("font-family: none;\r\n");
      out.write("letter-spacing: 1px;\r\n");
      out.write("margin: 10px 0 25px 0;\r\n");
      out.write("font-weight: 500;\r\n");
      out.write("font-size: xx-large;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"container-fluid text-center\" style=\"margin-top: 15px\">\r\n");
      out.write("\t<ul>\t\r\n");
      out.write("\t\t<li><a href=\"search-line\">Tin Tức</a></li>\r\n");
      out.write("\t\t<li><a href=\"search-line\">Sự Kiện</a></li>\r\n");
      out.write("\t\t<li><a href=\"search-line\">Hướng Dẫn</a></li>\r\n");
      out.write("\t\t<li><a href=\"search-line\">Liên Hệ</a></li>\r\n");
      out.write("\t\t<li><a href=\"search-line\">Trang Chủ</a></li>\t\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("<header style=\"background-image: url('imgs/header.jpg')\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t<h2>TÌM KIẾM TUYẾN ĐƯỜNG</h2>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 form-group\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" type=\"text\" id=\"day\" name=\"day\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Ngày\" /> <span id=\"dayerr\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 form-group\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" type=\"text\" id=\"month\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Tháng\" /> <span id=\"montherr\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-4 form-group \">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" type=\"text\" id=\"year\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Năm\" /> <span id=\"yearerr\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 form-group\">\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" id=\"from\" required>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">Lựa chọn điểm đi</option>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</select> <span id=\"fromerr\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 form-group\">\r\n");
      out.write("\t\t\t\t\t<select class=\"form-control\" id=\"to\" required>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">Lựa chọn điểm đến</option>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</select> <span id=\"toerr\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button onclick=\"search()\" id=\"myBtn\" class=\"btn btn-danger\" style=\"width: 150px; height: 40px; margin-top: 30px\">SEARCH</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<br>\r\n");
      out.write("  <div id=\"result\" class=\"modal\" >\r\n");
      out.write("    <div class=\"modal-window large\">  \r\n");
      out.write("    <span class=\"close\" onClick=\"closePopup()\">&times;</span>\r\n");
      out.write("    <h3 class=\"text-center h1TimKiem\">KẾT QUẢ TÌM KIẾM TUYẾN ĐƯỜNG</h3>\r\n");
      out.write("    <div class=\"abc text-center\" style=\"background-image: url('imgs/222.jpg')\">\r\n");
      out.write("    \r\n");
      out.write("\t<table class=\"table table-responsive container\" id=\"lineTable\" style=\"background-color: #6b5c5c82;margin-top: 10px;border-radius: 20px;border-collapse: inherit\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>ID tuyến đường</th>\r\n");
      out.write("\t\t\t<th>Điểm đi</th>\r\n");
      out.write("\t\t\t<th>Điểm đến</th>\r\n");
      out.write("\t\t\t<th>Hàng ghế</th>\r\n");
      out.write("\t\t\t<th>Số ghế trống</th>\r\n");
      out.write("\t\t\t<th>Giá cước</th>\r\n");
      out.write("\t\t\t<th>Đặt chỗ</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<a href=\"#\" class=\"fa fa-facebook\"></a>\r\n");
      out.write("<a href=\"#\" class=\"fa fa-twitter\"></a>\r\n");
      out.write("<a href=\"#\" class=\"fa fa-google\"></a>\r\n");
      out.write("<a href=\"#\" class=\"fa fa-linkedin\"></a>\r\n");
      out.write("<a href=\"#\" class=\"fa fa-youtube\"></a>\r\n");
      out.write("<a href=\"#\" class=\"fa fa-instagram\"></a>\r\n");
      out.write("<a href=\"#\" class=\"fa fa-pinterest\"></a>\t\t\t\t\t\t\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>   \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<h1 class=\"text-center h1TieuDe\">Khám phá\r\n");
      out.write("\t\tnhững điểm đến hàng đầu của chúng tôi</h1>\r\n");
      out.write("\t<div class=\"row\" style=\"margin-bottom: 25px\">\r\n");
      out.write("\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\" src=\"imgs/b1.jpg\">\r\n");
      out.write("\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t<h2>TP.Hồ CHÍ MINH</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\" >\r\n");
      out.write("\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t<div class=\"row\" style=\"margin-bottom: 15px\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\" src=\"imgs/danang.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>ĐÀ NẴNG</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\" style=\"margin-bottom: 25px\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\"  src=\"imgs/nhatrang.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>NHA TRANG</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\"  src=\"imgs/phuquoc.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>PHÚ QUỐC</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\"  src=\"imgs/hanoi.jpg\">\r\n");
      out.write("\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t<h2>HÀ NỘI</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\" style=\"margin-bottom: 25px\">\r\n");
      out.write("\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\"  src=\"imgs/hoian.jpg\">\r\n");
      out.write("\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t<h2>HỘI AN</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\"  src=\"imgs/dalat.jpg\">\r\n");
      out.write("\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t<h2>ĐÀ LẠT</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\" style=\"margin-bottom: 25px\">\r\n");
      out.write("\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\"  src=\"imgs/hue.jpg\">\r\n");
      out.write("\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t<h2>HUẾ</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\"  src=\"imgs/vungtau.jpg\">\r\n");
      out.write("\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t<h2>VŨNG TÀU</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<div class=\"hovereffect\">\r\n");
      out.write("\t\t\t\t<img class=\"img-responsive\" alt=\"tinhThanh\" src=\"imgs/cantho.jpg\">\r\n");
      out.write("\t\t\t\t<div class=\"overlay\">\r\n");
      out.write("\t\t\t\t\t<h2>CẦN THƠ</h2>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">LINK HERE</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\tfunction closePopup(){\r\n");
      out.write("\t\t$(\"#result\").css('display','none');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction search() {\r\n");
      out.write("\r\n");
      out.write("\t\tlet day = $('#day').val();\r\n");
      out.write("\t\tlet month = $('#month').val();\r\n");
      out.write("\t\tlet year = $('#year').val();\r\n");
      out.write("\t\tlet from = $('#from').val();\r\n");
      out.write("\t\tlet to = $('#to').val();\r\n");
      out.write("\t\tlet date = day + \"/\" + month + \"/\" + year;\r\n");
      out.write("\t\tlet d = new Date();\r\n");
      out.write("\t    var today = new Date();\r\n");
      out.write("\t\tvar dd = String(today.getDate()).padStart(2, '0');\r\n");
      out.write("\t\tvar mm = String(today.getMonth()).padStart(2, '0'); //January is 0!\r\n");
      out.write("\t\tvar yyyy = today.getFullYear();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar date1=new Date(year,month-1,day);\r\n");
      out.write("\t\tvar today1=new Date(yyyy,mm,dd);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar theDate = new Date();\r\n");
      out.write("\t\tvar today2 = new Date(theDate);\r\n");
      out.write("\t\ttoday2.setDate(today2.getDate() + 90);\r\n");
      out.write("\t\r\n");
      out.write("\t\t if (day == null || day == \"\"||day<0||day>31) {\r\n");
      out.write("\t         alert(\"Nhập vào ngày!\");\r\n");
      out.write("\t         return false;\r\n");
      out.write("\t         }\r\n");
      out.write("\t     else if (month == null || month == \"\"||month<0||month>12) {\r\n");
      out.write("\t\t     alert(\"Nhập vào tháng!\");\r\n");
      out.write("\t\t     return false;\r\n");
      out.write("\t\t     } \r\n");
      out.write("\t\t else if (year == null || year == \"\"||year<d.getFullYear()) {\r\n");
      out.write("\t\t\t alert(\"Nhập vào năm!\");\r\n");
      out.write("\t\t\t return false;   \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t else if (from == null || from == \"\") {\r\n");
      out.write("\t\t     alert(\"Vui lòng chọn điểm đi!\");\r\n");
      out.write("\t\t     return false;\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t\t else if (to == null || to == \"\") {\r\n");
      out.write("\t\t     alert(\"Vui lòng chọn điểm đến!\");\r\n");
      out.write("\t\t     return false;\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t\t else if (from==to) {\r\n");
      out.write("\t\t     alert(\"Điểm đi không thể trùng với điểm đến.\");\r\n");
      out.write("\t\t     return false;\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t\t else if (date1<today1) {\r\n");
      out.write("\t\t     alert(\"Ngày không hợp lệ.\");\r\n");
      out.write("\t\t     return false;\r\n");
      out.write("\t\t     }\r\n");
      out.write("\t\t   else if (date1>=today2) {\r\n");
      out.write("\t\t     alert(\"Bạn không thể đặt chỗ trước 90 ngày.\");\r\n");
      out.write("\t\t     return false;\r\n");
      out.write("\t\t     }  \r\n");
      out.write("\t\t else{\t\t\r\n");
      out.write("\t\t\t$(\"#result\").css('display','block');\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : 'search-result',\r\n");
      out.write("\t\t\t\tmethod : 'GET',\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tday : day,\r\n");
      out.write("\t\t\t\t\tmonth : month,\r\n");
      out.write("\t\t\t\t\tyear : year,\r\n");
      out.write("\t\t\t\t\tfrom : from,\r\n");
      out.write("\t\t\t\t\tto : to\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(responseJson) {\r\n");
      out.write("\t\t\t\t\tif (responseJson != null) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#lineTable\").find(\"tr:gt(0)\").remove();\r\n");
      out.write("\t\t\t\t\t\tvar table1 = $(\"#lineTable\");\r\n");
      out.write("\t\t\t\t\t\t$.each(responseJson,function(key, value) {\r\n");
      out.write("\t\t\t\t\t\t\tvar rowNew = $(\"<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\");\r\n");
      out.write("\t\t\t\t\t\t\trowNew.children().eq(0).text(value['idLine']);\r\n");
      out.write("\t\t\t\t\t\t\trowNew.children().eq(1).text(value['diemDi']);\r\n");
      out.write("\t\t\t\t\t\t\trowNew.children().eq(2).text(value['diemDen']);\r\n");
      out.write("\t\t\t\t\t\t\trowNew.children().eq(3).text(value['hangGhe']);\r\n");
      out.write("\t\t\t\t\t\t\trowNew.children().eq(4).text(value['soGheTrong']);\r\n");
      out.write("\t\t\t\t\t\t\trowNew.children().eq(5).text(value['price']);\r\n");
      out.write("\t\t\t\t\t\t\tif(Number(value['soGheTrong'])==0){\r\n");
      out.write("\t\t\t\t\t\t\t\trowNew.children().eq(6).text(\"Đã đủ chỗ.\");\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\trowNew.children().eq(6).html(\"<form action='chi-dinh-cho-ngoi' method='POST'><input type='hidden' name='idTuyenDuong' value='\"+value['idLine']+\"'/><input type='hidden' name='thoiGianKhoiHanh' value='\"+value['thoiGianKhoiHanh']+\"'/><input type='hidden' name='thoiGianDuKienDen' value='\"+value['thoiGianDuKienDen']+\"'/><input type='hidden' name='idBus' value='\"+value['idBus']+\"'/><input type='hidden' name='diemDi' value='\"+value['diemDi']+\"'/><input type='hidden' name='diemDen' value='\"+value['diemDen']+\"'/><input type='hidden' name='price' value='\"+value['price']+\"'/><input type='hidden' name='idTuyenDuong' value='\"+value['idLine']+\"'/><input type='hidden' name='ngayThang' value='\"+date+\"'/><button type='submit'class='btnDatCho'>ĐẶT CHỖ</button></form>\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\trowNew.appendTo(table1);\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(jqXHR, exception) {\r\n");
      out.write("\t\t\t\t\tconsole.log('Error occured!!');\r\n");
      out.write("\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/pages/common/footer1.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/pages/search/line.jsp(65,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${busStops}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/pages/search/line.jsp(65,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("busStop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${busStop.idBen}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${busStop.tinhThanh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/pages/search/line.jsp(73,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${busStops}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/pages/search/line.jsp(73,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("busStop");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${busStop.idBen}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${busStop.tinhThanh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
