/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-06-29 16:04:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1561823191150L));
    _jspx_dependants.put("/WEB-INF/pages/common/define.jsp", Long.valueOf(1561823191419L));
    _jspx_dependants.put("jar:file:/C:/magic/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/magic-frontend/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098685890000L));
    _jspx_dependants.put("jar:file:/C:/magic/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/magic-frontend/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098685890000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <style>\n");
      out.write("footer-row, .main-body, .main-header, .msg-wrapper, .sub-header {\r\n");
      out.write("    min-width: 1000px;\r\n");
      out.write("    max-width: 1300px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer1{\r\n");
      out.write("\t\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    overflow-y: scroll;\r\n");
      out.write("    word-break: break-word;\r\n");
      out.write("    \r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rest1.animate {\r\n");
      out.write("\tbackground-color: #1f1e1d;\r\n");
      out.write("    /*  transform: translateY(500px);*/\r\n");
      out.write("    animation: moveUp 1s cubic-bezier(.19,1,.22,1) forwards;\r\n");
      out.write("    transition: opacity 1s ease-in;\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-links {\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write(".w-100 {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".fl {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("footer-links .dib {\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    margin-bottom: 19px;\r\n");
      out.write("    color: #797979;\r\n");
      out.write("}\r\n");
      out.write("row {\r\n");
      out.write("    margin-right: 60px;\r\n");
      out.write("    text-align: left;}\r\n");
      out.write("    \r\n");
      out.write("   .dib {\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    margin-bottom: 19px;\r\n");
      out.write("    color: #797979;}\r\n");
      out.write(" .footer-links .dib {\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    margin-bottom: 19px;\r\n");
      out.write("    color: #797979;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".foot-wrapper {\r\n");
      out.write("    margin-left: 110px;\r\n");
      out.write("}\r\n");
      out.write("  .footer-links a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: #d7d7d7;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    margin-right: 50px;\r\n");
      out.write("}\r\n");
      out.write(".rights-cont {\r\n");
      out.write("    width: 335px;\r\n");
      out.write("    line-height: 27px;\r\n");
      out.write("    margin-right: 48px;\r\n");
      out.write("}\r\n");
      out.write(".fr {\r\n");
      out.write("    float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("user agent stylesheet\r\n");
      out.write("div {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write(".promotion {\r\n");
      out.write("    color: #b1babf;\r\n");
      out.write("    padding: 30px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row.fl {\r\n");
      out.write("    margin-right: 35px;\r\n");
      out.write("}\r\n");
      out.write(".footer-links a:hover {\r\n");
      out.write("color: #d7d7d780;\r\n");
      out.write("\t\r\n");
      out.write("}\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\"  style=\"background-color:#1f1e1d\">\r\n");
      out.write("<div class=\"footer1-row\">\r\n");
      out.write("    <div class=\"clearfix promotion  main-body rest1 animate\">\r\n");
      out.write("        <div class=\"w-100 pR fl footer-links\">\r\n");
      out.write("                <div class=\"dib foot-wrapper\">\r\n");
      out.write("                    <div class=\"row fl\">\r\n");
      out.write("                        <div class=\"dib\">\r\n");
      out.write("                            Giới thiệu về Magic Bus\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <a href=\"\" target=\"_blank\">About Us</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Contact Us</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Mobile Version</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Magic Bus on Mobile</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Sitemap</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Offers</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Careers</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Values</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row fl\">\r\n");
      out.write("                        <div class=\"dib\">\r\n");
      out.write("                            Thông tin\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">T &amp; C</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Privacy Policy</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">FAQ</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Blog</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Agent Registration</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Insurance Partner</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row fl\">\r\n");
      out.write("                        <div class=\"dib\">\r\n");
      out.write("                          Trang web toàn cầu\r\n");
      out.write("                        </div>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">India</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Singapore</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Malaysia</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Indonesia</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Peru</a>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">Colombia</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"fr rights-cont\">\r\n");
      out.write("                <div class=\"img-cont\">\r\n");
      out.write("                    <img src=\"imgs/r_logo_1.png\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"text-align: justify\">\r\n");
      out.write("                    Magic Bus là dịch vụ đặt vé xe buýt trực tuyến lớn nhất thế giới được tin tưởng bởi hơn 17 triệu khách hàng hài lòng trên toàn cầu. Magic Bus cung cấp dịch vụ đặt vé xe buýt thông qua trang web, ứng dụng di động iOS và Android cho tất cả các tuyến chính.\r\n");
      out.write("                </div>\r\n");
      out.write("                    <div id=\"social-media\">\r\n");
      out.write("    <a target=\"_blank\" href=\"\"><span class=\"fbicon icon-Facebook\"></span></a>\r\n");
      out.write("    <a target=\"_blank\" href=\"\"><span class=\"twittericon icon-Twitter\"></span></a>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                <div style=\"float: left\">\r\n");
      out.write("                    <span>Ⓒ</span>\r\n");
      out.write("                        <span>  2019 Magic Bus Bảo lưu mọi quyền</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>      \r\n");
      out.write("                    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<br> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
